sourcegraph/scip

renovate.json
=> Fix prettier check broken by renovate.

cmd/Readme.md
Wording borrowed from the announcement blog post draft.
n/a
=> docs: Update Readme to provide some context.

.gitignore
=> Add scip binary at root to .gitignore.

cmd/Readme.md
=> docs: Update Readme with links + case convention.

cmd/Readme.md
Forgot this earlier in #45.
n/a
=> docs: Remove TODO from Readme.

.github/workflows/project-board.yml
=> Automatically add issues to Code Intel Project Board

Development.md, Readme.md
=> docs: Add notes on debugging + consuming SCIP.

Readme.md, bindings/rust/Cargo.toml
=> rust: add license and description

bindings/rust/Cargo.toml, bindings/rust/src/mod.rs, bindings/rust/src/symbol.rs
=> rust: expose writer function and some new helpers

Development.md
All tests should just continue to pass.
=> fix: view -> print in docs

Readme.md, cmd/main.go, cmd/main_test.go, go.mod, go.sum
https://cli.urfave.org/v2/examples/version-flag/
Fixes #96 (until next time).
=> Use native `--version` support in `urfave/cli/v2`

cmd/tests/reprolang/bindings/go/repro/ast.go
=> test: Remove debug print statement.

Development.md
=> docs: Document how to publish a release + add index to doc.

Readme.md
=> docs: Mention CLI reference after installation

dev/publish-release.sh
This did work for the v0.2.2 release.
=> fix: Fix bugs in release script.

bindings/go/scip/canonicalize.go, bindings/go/scip/flatten.go, bindings/go/scip/sanitize.go, bindings/go/scip/sort.go, bindings/go/scip/sort_test.go
See https://github.com/sourcegraph/sourcegraph/pull/50287.
N/A.
=> Move SCIP utilities from `sourcegraph/sourcegraph`

bindings/rust/src/symbol.rs
=> rust: fix symbol parse and emit for empty packages

bindings/rust/src/symbol.rs
=> rust: fix local symbol parse and emit with locals

bindings/rust/src/symbol.rs
=> rust: fix emiting escaped symbols

bindings/go/scip/symbol.go, bindings/go/scip/symbol_test.go
It doesn't crash now :clueless:
=> go bindings: Don't panic on half-finished descriptors

docs/CLI.md
=> test: fix out-of-sync documentation

bindings/go/scip/parse.go, bindings/go/scip/parse_test.go
=> bindings/go: Handle nil visit functions properly when streaming

Readme.md
=> docs: Update README for recent changes

.github/workflows/protobuf.yml, .tool-versions, bindings/go/scip/scip.pb.go, go.mod
=> chore: Bump Go version

.github/workflows/release.yml, Development.md, bindings/rust/Cargo.toml, dev/publish-release.sh
Fixes #28
Will create a new release after merging this.
=> ci: Automate crate releases

.github/workflows/golang.yml, docs/CLI.md
=> fix: Fix version number in CLI.md

CHANGELOG.md
See: https://github.com/sourcegraph/scip/pull/218#discussion_r1381659821
Race condition in PR review.
- NA
=> docs: add missing entry for 0.3.2 to CHANGELOG.md

package.json
See suggestion here: https://github.com/prettier/prettier/issues/3709#issuecomment-356851836
CI passes
=> chore: Use stable prettier path instead of direct one

.gitattributes
=> chore: Fix generated file path in .gitattributes

bindings/go/scip/canonicalize.go, bindings/go/scip/sort.go, bindings/go/scip/sort_test.go, go.mod, go.sum
Also add clearer documentation related to guarantees around
document canonicalization.
Added property-based tests
=> feat: Add utility function for binary search based on symbol names

.github/workflows/build-env-docker.yml
Follow-up to https://github.com/sourcegraph/scip/pull/279
Check results after merging to `main`.
=> ci: Fix workflow breakage on version bump (attempt 2)
