- Development.md
- bindings/go/scip/convert.go
- cmd/main.go
- cmd/main_test.go
Mostly a no-op, exposing conversion functionality as a public API.
Existing tests are passing, double-checked that `src-cli` compiles fine
in https://github.com/sourcegraph/src-cli/pull/742 after using a replace
directive to point to my local `scip` repo with this patch.
> Move SCIP to LSIF conversion into library.

- .gitignore
- cmd/convert.go
- cmd/main.go
- cmd/main_test.go
- go.mod
- go.sum
Makes progress towards #3.
I'm using `convert` as the subcommand name so that we don't need to
add another subcommand if/when we add support for LSIF → SCIP
conversion in the future.
I'll add a `snapshot` subcommand in a subsequent PR.
Added automated tests. I didn't add tests for stdin/stdout because it
felt a little cumbersome (e.g. we could pass in stdin/stdout to `convertMain`;
using different stdin/stdout in the tests) but I can add those if you think
we should test that too, NBD.
> cli: Add convert subcommand and help text.

- Readme.md
- cmd/Readme.md
- cmd/main.go
- cmd/main_test.go
The Readme has a comment explaining why I'm using a symlink at
the root. I've manually confirmed that GitHub will render the
Readme even if it is a symlink.
This PR is stacked on top of:
* #5 : (first commit of this PR)
Ran existing tests, manually ran the `--help` subcommand.
> cli: Move help text to Readme and embed Readme in CLI.

- bindings/go/scip/testutil/format.go
- bindings/go/scip/testutil/format_test.go
The old code does incorrect index comparisons and can also cause
out-of-bounds indexing when both source ranges are identical.
Added unit tests.
> bindings/go: Fix bug in range comparison.

- .github/workflows/formatting.yml
Renovate managed to bypass the formatting check earlier because the formatting check
didn't trigger for JSON only changes.
n/a
> ci: Run prettier for JSON only changes.

- .github/workflows/golang.yml
- .github/workflows/haskell.yml
- .github/workflows/protobuf.yml
- .github/workflows/reprolang.yml
- .github/workflows/rust.yml
- .github/workflows/typescript.yml
The names show up in the UI, and having a bunch of jobs all
named 'check' makes it impossible to distinguish which job
is being referred to.
n/a
> ci: Give workflow jobs more useful names.

- cmd/convert.go
Somehow I forgot to add the dashes here.
Manually tested, compared with other reads from `parsedArgs`.
> cli: Add missing -- when reading flags.

- bindings/go/scip/convert.go
- cmd/tests/snapshots/input/implementation/animal.repro
- cmd/tests/snapshots/output/implementation/animal.repro
- cmd/tests/snapshots/output/implementation/dump.lsif
Previously, doing "Find implementations" only showed one result when there were multiple results available. Now, all available results should be shown after this fix.
Opening this as a draft since it's still not working 100% and I'm gonna continue with this PR tomorrow.
See newly added snapshot tests. I'm also manually testing this change by uploading the generated dump.lsif to Sourcegraph here https://sourcegraph.com/github.com/sourcegraph/scip-typescript@34337f2fa29d3a83c71814458d19741ae4f21db9/-/blob/snapshots/input/syntax/src/inheritance2.ts?L2:3&subtree=true#tab=implementations_typescript
> Fix a bug related to textDocumentation/implementation

- bindings/go/scip/convert.go
Manually review the diff to confirm the new behavior is desired.
> Correctly convert scip-typescript moniker scheme to npm

- bindings/rust/Cargo.toml
Cargo only does **exact** version when you have `=` sign in front of it.
> fix: specify exact version in Cargo.toml

- cmd/convert.go
- cmd/main.go
- cmd/snapshot.go
Previously, the default value was unset because we only configured the
"(default: X)" --help message.
I manually tested the change since we don't have integration tests yet.
> Use `Value` instead of `DefaultText` for default values

- .gitignore
> Avoid gitignore applying to bindings/go/scip.

- bindings/go/scip/convert.go
Don't crash if that's the case.
See the index in https://github.com/sourcegraph/scip/issues/68.
Tested with an index generated by scip-ruby.
> fix: SCIP documents may be empty.

- Readme.md
This pr just adds a few notes about installing the cli for those that
aren't as familiar with Go.
> docs: add some install instructions

- bindings/go/scip/symbol.go
> fix: Avoid out-of-bounds with unbalanced identifier escapes.

- bindings/rust/Cargo.toml
Repository links are useful if you want to figure out where a particular crate is hosted. I have wondered the same thing and was able to find this repository, but it would have been easier if I could just have clicked the link on docs.rs.
> Add github repository link

- Development.md
- cmd/main_test.go
Based on convo in Zoom, this should help test code nav behavior quickly compared to having to replace strings manually.
Tested this locally.
> reprolang: Add flag to use abspaths in LSIF indexes.

- Development.md
- Readme.md
- cmd/lint.go
- cmd/lint_test.go
- cmd/main.go
- go.sum
Fixes #90.
Tested manually against an index generated by scip-ruby, and it did flag a bunch of errors.
TODO:
> cli: Add lint subcommand.

- Readme.md
- cmd/main_test.go
- docs/CLI.md
I've moved out the CLI reference into a separate doc to reduce clutter.
The lack of mention of indexers was flagged on HN: https://news.ycombinator.com/item?id=33082636
n/a
> docs: Rework README to mention indexers.

- cmd/main_test.go
- go.mod
- go.sum
New version of `urfave/cli` is released with fixes for trailing whitespace.
https://github.com/urfave/cli/discussions/1518
```
cd cmd
go test
```
> Bump `urfave/cli` and remove redundant code

- bindings/go/scip/symbol_formatter.go
- bindings/go/scip/testutil/format.go
- cmd/snapshot.go
Previously, the `scip snapshot` command failed if there was a symbol that wasn't parseable. This was unhelpful when trying to debug why navigation was not working as expected (which is the main situation where I use `scip snapshot`). Unparseable symbols are not invalid, they just don't work with cross-repo navigation. To fail fast like before, there's a new `scip snapshot --strict` flag that fails if there's a parser error.
Manually tested locally.
> Snapshot: don't fail on unparseable symbols.

- bindings/go/scip/testutil/format.go
Adds the following
```
switch concreteValue := interfaceValue.(type) {
//        ^^^^^^^^^^^^^ definition local 2
//        override documentation This is a case thing
```
> add override documentation

- bindings/rust/src/symbol.rs
As documented at https://doc.rust-lang.org/std/macro.dbg.html the dbg! macro unconditionally prints its argument to stderr, even in release builds.  (It is not possible to quiet it through use of RUST_LOG.)
Presumably this was accidentally left in.
> Remove debugging output from symbol.rs that cannot otherwise be disabled.

- bindings/rust/Cargo.lock
- bindings/rust/Cargo.toml
- bindings/rust/src/symbol.rs
parse_symbol was failing on a bunch of rust symbols that look like "rust-analyzer cargo test_rust_dependency 0.1.0 MyType#new()." with `Err(InvalidIdentifier("method disambiguator"))`.
The problem is that the method descriptor was attempting to use peek to look for the character after the opening "(" to see if it was a ")", but the index had already been incremented, so peek would see the "." closing character instead of the ")".
I also have a change in this patch to disable automatic doctests because `cargo test` is failing for me locally without this because it seems to view the inlined protobuf schema as a doctest and reasonably has trouble parsing the schema as valid rust code.  I am not able to delve into the general machinery around the "generated" directory at this time, but it …
> [rust bindings] Allow zero-length method disambiguation.

- cmd/snapshot.go
> feat: add comment-syntax flag

- bindings/go/scip/symbol.go
- bindings/go/scip/symbol_formatter.go
- bindings/go/scip/symbol_test.go
> chore: move to non-deprecated symbol

- bindings/go/scip/testutil/format.go
- cmd/main_test.go
- cmd/snapshot.go
This option can be useful if the scip file is produced inside a docker container, and the project root in the file points to a non-existent location.
Manual testing
> Add --project-root option to override the root inside scip files

- .github/workflows/haskell.yml
- .github/workflows/protobuf.yml
- bindings/haskell/src/Proto/Scip.hs
- bindings/haskell/src/Proto/Scip_Fields.hs
- buf.gen.yaml
- dev/proto-generate.sh
Supersedes https://github.com/sourcegraph/scip/pull/146
Previously, the Haskell bindings became outdated as soon as we made changes to the SCIP spec. This PR adds Haskell binding generation to the `proto-generate.sh` script so that the Haskell bindings are automatically kept up-to-date as we make changes to the spec.
Green CI.
> Automatically generate Haskell bindings

- bindings/rust/src/symbol.rs
Macros end in an exclamation point. Currently parsing one results in a MissingDescriptor error, for example:
```rust
dbg!(scip::symbol::parse_symbol("rust-analyzer cargo std https://github.com/rust-lang/rust/library/std macros/print!"));
```
> [rust bindings] parse macro symbols

- bindings/go/scip/canonicalize.go
- bindings/go/scip/canonicalize_test.go
- bindings/go/scip/flatten_test.go
[slack context with sentry error](https://sourcegraph.slack.com/archives/CMBA8F926/p1687875505846289)
> go bindings: Remove occurrences with empty ranges during canonicalization

- bindings/go/scip/memtest/DO_NOT_ADD_NEW_TEST_FILES_HERE
- bindings/go/scip/memtest/low_mem_test.go
We rely on low memory usage in Sourcegraph. https://github.com/sourcegraph/sourcegraph/pull/53828
So add a test to avoid regressing memory usage.
Added a new test
> bindings/go: Add memory usage test for streaming parser

- bindings/go/scip/symbol_formatter.go
- bindings/go/scip/symbol_formatter_test.go
We were failing to escape the SCIP identifier names on formatting.
New unit tests
> formatter: Fix escaping logic

- cmd/main_test.go
- docs/CLI.md
- go.mod
- go.sum
Fixed in https://github.com/urfave/cli/releases/tag/v2.19.2
```sh
scip snapshot -h
```
**Before**
```
OPTIONS:
--comment-syntax value  Comment syntax to use for snapshot files (default: "//")
--from value            Path to SCIP index file (default: "index.scip")
--help, -h              show help (default: false)
--project-root value    Override project root in the SCIP file. For example, this can be helpful when the SCIP index was created inside a Docker image or created on another computer
--strict                If true, fail fast on errors (default: true)
--to value              Path to output directory for snapshot files (default: "scip-snapshot")
```
**After**
```
OPTIONS:
--from value            Path to SCIP index file (default: "index.scip")
--to value              Path to output …
```
> Stop sorting CLI options

- bindings/go/scip/testutil/format.go
- cmd/main.go
- cmd/snapshot.go
- cmd/stats.go
Workaround for https://github.com/sourcegraph/scip/issues/98
This shares logic with `bindings/go/scip/testutil/format.go`, but I haven't found the best place to put this shared code.
```sh
$ go build -o scip ./cmd && ./scip stats --from /tmp/index.scip --project-root /data/s/gdk
{
"documents": 222,
"linesOfCode": 14789,
"occurrences": 11324,
"definitions": 2908
}
```
```sh
$ go build -o scip ./cmd && ./scip stats --from /tmp/index.scip                          
2023/07/19 17:51:48 Project root [/s/gdk] doesn't exist, using current working directory [/home/anatoli/delme/scip] instead. To override this behaviour, specify --project-root=<folder> option
2023/07/19 17:51:48 error counting stats: lstat /home/anatoli/delme/scip/support/compare.rb: no such file or directory 
```
> Add `--project-root` flag to `scip stats`

- .github/workflows/protobuf.yml
- dev/proto-generate.sh
There seems to be a build failure with ghc-source-gen-0.4.4.0 when
using GHC 8.10, so attempt to tell cabal to use an older version.
```
src/GHC/SourceGen/Module.hs:191:41: error:
Error:     Variable not in scope: unqual :: OccNameStr -> RdrNameStr
|
191 |                     (map (wrappedName . unqual) cs)
|                                         ^^^^^^
Error: cabal: Failed to build ghc-source-gen-0.4.4.0 (which is required by
exe:proto-lens-protoc from proto-lens-protoc-0.7.1.1). See the build log above
for details.
```
Source: https://github.com/sourcegraph/scip/actions/runs/7322644181/job/19944384186?pr=226
CI passes
> ci: Try using older version of ghc-source-gen

- cmd/scip/stats.go
- go.mod
- go.sum
Fixes https://github.com/sourcegraph/scip/issues/239
Fixes ENG-23701
Ran it locally, it prints the following output for a Chromium index.
```
{
"documents": 103101,
"documentSizes": {
"Percentiles": {
"50": 10994,
"90": 116245,
"95": 224756,
"99": 747849,
"99.9": 2806214
},
"mean": 57509,
"stddev": 287100,
"max": 43255012,
"sum": 2147483647,
"comment": "sizes are in bytes"
},
"linesOfCode": 0,
"occurrences": 80690299,
"occurrenceCounts": {
"Percentiles": {
"50": 145,
"90": 1611,
"95": 3043,
"99": 10044,
"99.9": 38139
},
"mean": 782,
"stddev": 3985,
"max": 589825,
"sum": 80690299,
"comment": ""
},
"definitions": 10405028,
"definitionCounts": {
"Percentiles": {
"50": 31,
"90": 206,
"95": 361,
"99": 1095,
"99.9": 3966
},
"mean": 100,
"stddev": 395,
"max": 43055,
"sum": 10405028,
"comment": …
```
> stats: Measure percentiles, max etc.

- dev/proto-generate.sh
In some configurations, 'cabal install' will install the binary
into the current directory instead of in the global directory
on 'PATH', which can cause the haskell step to fail. Pass
the --installdir flag to avoid that.
Covered by existing codegen
> codegen: Pass --installdir flag to cabal install

- CHANGELOG.md
- bindings/go/scip/canonicalize.go
- bindings/go/scip/position.go
- bindings/go/scip/position_test.go
- bindings/go/scip/sort.go
- bindings/go/scip/sort_test.go
- bindings/go/scip/testutil/format.go
- cmd/scip/lint.go
- cmd/scip/lint_test.go
- go.mod
- go.sum
The Range type in this package is 128-bits, whereas some Range types
in the Sourcegraph packages are 256-bits. Additionally, some of the APIs
would previously work using `*Range` instead of just `Range`.
This PR fixes the pointer-based APIs and adds commonly used APIs
for Range and Position so we don't have to keep re-implementing them.
We also add documentation that ranges are half-open, not closed.
Added new tests
> bindings/go: Add common APIs for Range and Position

- .github/workflows/build-env-docker.yml
- dev/Dockerfile.bindings
This PR definitively fixes the multi-platform image generation, by using a matrix build.
- This workflow will run as part of main
- I also manually tested it – here's the published image(s): https://github.com/sourcegraph/scip/pkgs/container/scip-bindings-env
> Use matrix build for multi-platform Docker build

- .github/workflows/build-env-docker.yml
I incorrectly missed the fact that we actually did have a matrix
build when reviewing https://github.com/sourcegraph/scip/pull/272
Let's see if this PR fixes the job after merging into main
> ci: Fix workflow breakage on version bump

- .tool-versions
- cmd/scip/tests/reprolang/package.json
- yarn.lock
The old nan version caused a prettier failure in CI.
The old Yarn version triggered a warning when running locally:
warning Your current version of Yarn is out of date. The latest version is "1.22.22", while you're on "1.22.17".
CI prettier
> chore: Bump Yarn and nan package versions

- cmd/scip/main_test.go
- cmd/scip/test.go
The new `test` command introduced in [this PR](https://github.com/sourcegraph/scip/pull/236) contained some issues when rendering the failure list.
Upon failure, this is what the output would look like
```console
✗ lib/functions.dart
Failure - row: 2, column: 2
Expected: 'definition asdf'
Actual:
- 'reference scip-dart pub scip_dart_test 1.0.0 lib/`functions.dart`/withReturn().'
- 'diagnostic Information'
''withReturn' is deprecated and shouldn't be used. a.'    Failure - row: 14, column: 2
Expected: 'reference scip-dart pub dart:core 2.19.0 dart:core/`int.dart`/int#'
Actual:
- 'reference scip-dart pub dart:core 2.19.0 dart:core/`int.dart`/int#'✗ Missing documents in SCIP index
test/.dart_tool/package_config.json
test/pubspec.lock
test/pubspec.yaml
```
After this change, the output now …
> Resolved formatting issues in test command output

- DESIGN.md
- README.md
> docs: Add DESIGN.md

- bindings/go/scip/sort.go
This should generally be faster than manual `<`/`>`.
https://github.com/golang/go/issues/61725
Covered by existing tests
> chore: Use faster 3 way string comparison

- cmd/scip/lint.go
- cmd/scip/tests/reprolang/bindings/go/repro/ast.go
- cmd/scip/tests/reprolang/bindings/go/repro/indexer.go
- cmd/scip/tests/reprolang/bindings/go/repro/namer.go
- cmd/scip/tests/snapshots/input/global-workspace/hello.repro
- cmd/scip/tests/snapshots/input/local-document/local2.repro
- cmd/scip/tests/snapshots/output/global-cross-repo/reference.repro
- cmd/scip/tests/snapshots/output/global-workspace/hello.repro
- cmd/scip/tests/snapshots/output/local-document/local2.repro
When trying to use repro with relationships, noticed that
we would incorrectly set a bad symbol name instead of
propagating the error in name resolution.
n/a
> fix: Propagate errors when creating repro SCIP index

- dev/proto-generate.sh
I'm not 100% sure as to why --locked works given that
there is no Cargo.lock either at the root of this repo
or in the rust-protobuf repo, but it seems to fix the
installation error where a dependency 'home v0.5.11'
gets picked up which ends up requiring Rust 1.81+
I saw a failure in an unrelated PR earlier here:
https://github.com/sourcegraph/scip/actions/runs/12357387613/job/34485511480?pr=297
Check that CI passes
> chore: Fix protoc-gen-rs installation error

- cmd/scip/tests/reprolang/bindings/go/repro/indexer.go
- cmd/scip/tests/reprolang/bindings/go/repro/namer.go
When trying to enter definitions, we were incorrectly dropping symbol
parsing errors. This can lead to failures downstream when attempting
Find references on a SCIP index.
n/a
> fix: Propagate errors when creating repro SCIP index (part 2)

- .tool-versions
- CHANGELOG.md
- bindings/rust/Cargo.toml
- cmd/scip/tests/reprolang/Cargo.toml
> chore: Bump MSRV

- .github/workflows/formatting.yml
- DESIGN.md
Switched to GitHub action dedicated to running prettier formatter at a fixed version.
Changed **/*.{js,json,md,ts,yaml,yml} to **.{js,json,md,ts,yaml,yml} to ensure root-level files are also formatted, matching the on.pull_request.paths filters
Formatted files.
N/A
> Fix prettier formatting GitHub action

- .github/workflows/scip-examples.yaml
Added https://github.com/google/guava to SCIP index uploads. Used matrix strategies - I think it'll pay off as we add more repositories. The only disadvantage is that we have some steps strictly related to scip binary (but not too many).
Part of GRAPH-1255. Used `amp` for editing: [thread](https://ampcode.com/threads/T-9377a689-7d20-47bd-b80c-ad46731df1b0).
- https://github.com/sourcegraph/scip/actions/runs/17134017105
- https://github.com/sourcegraph/scip/actions/runs/17134165480
> feat: Upload google/guava and apache/pekko SCIP index

- .github/workflows/scip-examples.yaml
Manual: https://github.com/sourcegraph/scip/actions/runs/17608744651/job/50025531308
> Add Homebrew to precise code-nav examples
